### ISSUE TITLE
Spawn building positioning.

### ISSUE THREAD

**Issue by RoRAustin** [RigsOfRods-Community/community-map#25]
The position of this building is blocking the roadway.

![](http://www.animos.us/uploads/937662892.jpg)

**Comment by DarthCainRor** [comment]
Will be fixed soon.

![screenshot_2016-06-01_03-36-17_1](https://cloud.githubusercontent.com/assets/10333582/15703320/3cdc8138-27aa-11e6-8a02-f46db962f2e6.png)
